### ISSUE TITLE
Not suit with 3.10.x on iOS

### ISSUE THREAD

**Issue by sunjianan9900** [MohamedAbd0/stroke_text#1]
not work with impller

**Comment by Jithesh-kumar** [comment]
strokeWidth not work 
![Simulator Screenshot - iPhone 15 Pro Max - 2023-12-29 at 11 27 19](https://github.com/MohamedAbd0/stroke_text/assets/78300199/dd0d8026-aec6-449e-8101-881bb731077b)

**Comment by MohamedAbd0** [comment]
@sunjianan9900  @Jithesh-kumar please provide me with your source code.
