### ISSUE TITLE
Missing Alignment Support in StrokeText

### ISSUE THREAD

**Issue by Supreme-Soft** [MohamedAbd0/stroke_text#3]
Encountered an issue with the `StrokeText` widget. Unable to set horizontal alignment using `TextAlign`; it seems the widget lacks support for AlignmentGeometry.

**Issue:** The named parameter `'textAlign'` isn't defined.

`StrokeText(
  text: 'Example Text',
  textStyle: TextStyle(fontSize: 20),
  textAlign: TextAlign.center, // <-- This is not working
)
`

**Expected Behavior:**
Setting `textAlign `should horizontally align the text within the `StrokeText `widget.

**Actual Behavior:**
The `StrokeText `widget does not respond to `textAlign `for horizontal alignment.

Any suggestions would be appreciated.

**Comment by MohamedAbd0** [comment]
it adds in new version (version: 0.0.2)
